BEGIN;
CREATE TEMP TABLE ops_test_results(check_name text,passed boolean);
DO $$
DECLARE a uuid;vu uuid;v uuid;ru uuid;rid uuid;p uuid:=gen_random_uuid();o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();req jsonb;r jsonb;pin text;payload jsonb;address text:=E'Rollback test, Gazimagusa\nMap pin: https://www.google.com/maps?q=35,33';replay json;
BEGIN
 SELECT user_id INTO a FROM public.admin_users LIMIT 1;
 SELECT u.user_id,u.vendor_id INTO vu,v FROM public.vendor_users u WHERE NOT EXISTS(SELECT 1 FROM public.admin_users WHERE user_id=u.user_id) LIMIT 1;
 SELECT user_id,rider_id INTO ru,rid FROM public.rider_users LIMIT 1;
 IF a IS NULL OR vu IS NULL OR ru IS NULL THEN RAISE EXCEPTION 'Linked roles are required';END IF;
 UPDATE public.vendors SET active=true,accepting_orders=true WHERE id=v;
 UPDATE public.riders SET active=true,available=true WHERE id=rid;
 INSERT INTO public.products(id,vendor_id,name,price,available) VALUES(p,v,'Transactional workflow test meal',200,true);
 INSERT INTO public.vendor_pickup_pins(vendor_id,latitude,longitude) VALUES(v,35,33) ON CONFLICT(vendor_id) DO UPDATE SET latitude=35,longitude=33;
 UPDATE public.megjet_launch_settings SET store_active=true,open_time='00:00',close_time='23:59',min_order=0 WHERE id=1;
 UPDATE public.megjet_delivery_coverage SET enabled=false WHERE id=1;
 payload:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2,'customizations','{}'::jsonb));
 PERFORM set_config('request.jwt.claim.sub',vu::text,true);
 PERFORM public.create_customer_order_retry(o,'Rollback test','0000000000',address,'Cash on Delivery',null,payload);
 replay:=public.create_customer_order_retry(o,'Rollback test','0000000000',address,'Cash on Delivery',null,payload);
 IF (replay->>'replayed')::boolean IS NOT TRUE THEN RAISE EXCEPTION 'Lost-response retry failed';END IF;
 BEGIN PERFORM public.create_customer_order_retry(o,'Rollback test','0000000000',address,'Cash on Delivery',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',3)));RAISE EXCEPTION 'Changed cart allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Changed cart allowed' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Checkout and lost-response retry',true);
 PERFORM set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
 BEGIN PERFORM public.admin_operations_report();RAISE EXCEPTION 'Report leaked';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'Admin access required' THEN RAISE;END IF;END;
 BEGIN PERFORM public.customer_request_order_service(o,'cancellation','Wrong account');RAISE EXCEPTION 'Other customer allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'Order not found in this account' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Account ownership and admin report protection',true);
 PERFORM set_config('request.jwt.claim.sub',a::text,true);
 BEGIN PERFORM public.admin_set_order_status(o,'delivered');RAISE EXCEPTION 'Skipped stages allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Skipped stages allowed' THEN RAISE;END IF;END;
 PERFORM public.admin_set_order_status(o,'confirmed');
 PERFORM set_config('request.jwt.claim.sub',vu::text,true);
 PERFORM public.set_vendor_order_status(o,'preparing');PERFORM public.set_vendor_order_status(o,'ready_for_pickup');
 PERFORM public.vendor_save_preparation(v,32);
 IF (SELECT preparation_minutes FROM public.vendors WHERE id=v)<>32 THEN RAISE EXCEPTION 'Preparation save failed';END IF;
 INSERT INTO ops_test_results VALUES('Vendor preparation controls and order stages',true);
 PERFORM set_config('request.jwt.claim.sub',a::text,true);PERFORM public.admin_assign_rider_to_order(o,rid);
 PERFORM set_config('request.jwt.claim.sub',ru::text,true);PERFORM public.rider_accept_delivery(o);
 SELECT delivery_pin INTO pin FROM public.delivery_security WHERE order_id=o::text;
 BEGIN PERFORM public.rider_complete_delivery(o::text,CASE WHEN pin='0000' THEN '1111' ELSE '0000' END,null,true);RAISE EXCEPTION 'Wrong PIN allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Wrong PIN allowed' THEN RAISE;END IF;END;
 PERFORM public.rider_complete_delivery(o::text,pin,null,true);
 IF NOT EXISTS(SELECT 1 FROM public.orders WHERE id=o AND status='delivered' AND payment_status='paid') THEN RAISE EXCEPTION 'Delivery failed';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.rider_earnings e JOIN public.orders o1 ON o1.id::text=e.order_id WHERE o1.id=o AND e.amount=o1.delivery_fee) THEN RAISE EXCEPTION 'Rider earning failed';END IF;
 BEGIN PERFORM public.rider_complete_delivery(o::text,pin,null,true);RAISE EXCEPTION 'Duplicate delivery allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Duplicate delivery allowed' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Assigned rider, delivery PIN, payment and earning',true);
 PERFORM set_config('request.jwt.claim.sub',a::text,true);
 PERFORM public.admin_record_rider_payment((SELECT id FROM public.rider_earnings WHERE order_id=o::text),'Rollback payment receipt');
 IF NOT EXISTS(SELECT 1 FROM public.rider_earnings WHERE order_id=o::text AND status='paid' AND paid_by=a AND paid_reference='Rollback payment receipt') THEN RAISE EXCEPTION 'Payment record failed';END IF;
 BEGIN PERFORM public.admin_record_rider_payment((SELECT id FROM public.rider_earnings WHERE order_id=o::text),'Duplicate receipt');RAISE EXCEPTION 'Duplicate payment recorded';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'This earning is already paid or unavailable' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Audited rider payment and duplicate rejection',true);

 PERFORM set_config('request.jwt.claim.sub',vu::text,true);
 req:=public.customer_request_order_service(o,'refund','Meal problem test');
 r:=public.customer_request_order_service(o,'refund','Duplicate request test');
 IF r->>'id'<>req->>'id' THEN RAISE EXCEPTION 'Duplicate refund created';END IF;
 EXECUTE 'SET LOCAL ROLE authenticated';
 IF NOT EXISTS(SELECT 1 FROM public.order_service_requests WHERE order_id=o) THEN RAISE EXCEPTION 'Customer cannot read own request';END IF;
 PERFORM set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
 IF EXISTS(SELECT 1 FROM public.order_service_requests WHERE order_id=o) THEN RAISE EXCEPTION 'RLS leaked customer request';END IF;
 EXECUTE 'RESET ROLE';
 INSERT INTO ops_test_results VALUES('Actual authenticated-role request RLS',true);

 PERFORM set_config('request.jwt.claim.sub',a::text,true);
 BEGIN PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'approve',100000,'Too high');RAISE EXCEPTION 'Excess refund allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Excess refund allowed' THEN RAISE;END IF;END;
 PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'approve',100,'Approved test');
 BEGIN PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'complete',0,'');RAISE EXCEPTION 'Receipt missing allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Receipt missing allowed' THEN RAISE;END IF;END;
 PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'complete',0,'Rollback receipt only');
 r:=public.admin_operations_report();
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r->'vendors') x WHERE x->>'vendor_id'=v::text) OR (r->>'refunds_completed')::numeric<100 THEN RAISE EXCEPTION 'Report totals failed';END IF;
 INSERT INTO ops_test_results VALUES('Refund limits, duplicate requests, returned record and report',true);
 PERFORM set_config('request.jwt.claim.sub',vu::text,true);
 PERFORM public.create_customer_order_retry(o2,'Rollback test','0000000000',address,'Cash on Delivery',null,payload);
 PERFORM set_config('request.jwt.claim.sub',a::text,true);PERFORM public.admin_set_order_status(o2,'confirmed');
 UPDATE public.orders SET payment_status='paid' WHERE id=o2;
 PERFORM set_config('request.jwt.claim.sub',vu::text,true);
 req:=public.customer_request_order_service(o2,'cancellation','Changed plans test');
 BEGIN PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'approve',0,'No');RAISE EXCEPTION 'Customer approved own request';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'Admin access required' THEN RAISE;END IF;END;
 PERFORM set_config('request.jwt.claim.sub',a::text,true);PERFORM public.admin_resolve_order_service((req->>'id')::uuid,'approve',0,'Approved cancellation');
 IF NOT EXISTS(SELECT 1 FROM public.orders WHERE id=o2 AND status='cancelled') OR NOT EXISTS(SELECT 1 FROM public.order_service_requests WHERE order_id=o2 AND kind='refund' AND status='approved') THEN RAISE EXCEPTION 'Cancellation refund queue failed';END IF;
 INSERT INTO ops_test_results VALUES('Admin cancellation and automatic paid-refund queue',true);
 PERFORM public.admin_save_delivery_coverage(true,35,33,1500);
 PERFORM public.quote_nearby_delivery(payload,E'Boundary test\nMap pin: https://www.google.com/maps?q='||(35+1500.0/111194.926644559)::text||',33');
 BEGIN PERFORM public.quote_nearby_delivery(payload,E'Outside test\nMap pin: https://www.google.com/maps?q=35.04,33');RAISE EXCEPTION 'Outside quote allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'Delivery is not available at this location' THEN RAISE;END IF;END;
 BEGIN PERFORM public.create_customer_order_retry(gen_random_uuid(),'Rollback test','0000000000',E'Outside test\nMap pin: https://www.google.com/maps?q=35.04,33','Cash on Delivery',null,payload);RAISE EXCEPTION 'Outside checkout allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm<>'Delivery is not available at this location' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Coverage boundary and server checkout protection',true);
 UPDATE public.megjet_delivery_coverage SET enabled=false WHERE id=1;
 UPDATE public.vendors SET accepting_orders=false WHERE id=v;
 BEGIN PERFORM public.create_customer_order_retry(gen_random_uuid(),'Rollback test','0000000000',address,'Cash on Delivery',null,payload);RAISE EXCEPTION 'Paused vendor allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Paused vendor allowed' THEN RAISE;END IF;END;
 UPDATE public.vendors SET accepting_orders=true WHERE id=v;UPDATE public.products SET available=false WHERE id=p;
 BEGIN PERFORM public.create_customer_order_retry(gen_random_uuid(),'Rollback test','0000000000',address,'Cash on Delivery',null,payload);RAISE EXCEPTION 'Sold-out item allowed';EXCEPTION WHEN OTHERS THEN IF sqlerrm='Sold-out item allowed' THEN RAISE;END IF;END;
 INSERT INTO ops_test_results VALUES('Paused vendor and sold-out checkout rejection',true);
 IF has_table_privilege('anon','public.order_service_requests','select') OR has_table_privilege('authenticated','public.order_service_requests','update') THEN RAISE EXCEPTION 'Request table permissions too broad';END IF;
 INSERT INTO ops_test_results VALUES('Private request table permissions',true);
END $$;
SELECT * FROM ops_test_results;
ROLLBACK;
