with photos(name,image_url) as(values
('Water & Ice','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-water-ice.jpg'),
('Drinks','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-drinks.jpg'),
('Snacks','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-snacks.jpg'),
('Food','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-food.jpg'),
('Meat & Chicken','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-meat-chicken.jpg'),
('Basic Foods','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-basic-foods.jpg'),
('Dairy & Breakfast','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-dairy-breakfast.jpg'),
('Bakery','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-bakery.jpg'),
('Fit & Form','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-fit-form.jpg'),
('Home Care','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-home-care.jpg'),
('Home Life','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-home-life.jpg'),
('Personal Care','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-personal-care.jpg'),
('Technology','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-technology.jpg'),
('Sexual Health','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-sexual-health.jpg'),
('Baby','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-baby.jpg'),
('Clothing','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-clothing.jpg'),
('Stationery','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-stationery.jpg'),
('Pet','https://assam152002.github.io/Megjet/assets/menu-photos/our-market-category-pet.jpg')
),updated as(update public.vendor_menu_categories c set image_url=p.image_url from photos p where c.vendor_id='06d76aea-1c94-5950-b621-22130e57ef75'::uuid and c.name=p.name and coalesce(c.image_url,'')='' returning c.name) select count(*) as updated_categories from updated;
